spring:
 cloud:
   gateway:
     routes:
       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/order/**
         filters:
           - AuthenticationFilter
           
           
       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/auth/**
     globalcors:
        add-to-simple-url-handler-mapping: true
 application:
   name: FOODKA-GATEWAY

     
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/